#ifndef LU_MTZR_SCHM_DSC_h
#define LU_MTZR_SCHM_DSC_h

enum MTZR_ID_SELECTORS{
ID_MTZR1,
ID_MTZR2,
ID_MTZR3 = ID_MTZR2

};
enum MTZR_ID_TMR_BIT{
    
    IDX_TMR_MTZR_IN,              IDX_TMR_MTZR_OUT, 
    //IDX_TMR_MTZR_IN_DEPENDENT,    IDX_TMR_MTZR_OUT_DEPENDENT,
    IDX_TMR_MTZR_IN_PR,           IDX_TMR_MTZR_OUT_PR,
    IDX_TMR_MTZR_IN_N_VPERED,     IDX_TMR_MTZR_OUT_N_VPERED,
    IDX_TMR_MTZR_IN_N_VPERED_PR,  IDX_TMR_MTZR_OUT_N_VPERED_PR,
    IDX_TMR_MTZR_IN_N_NAZAD,      IDX_TMR_MTZR_OUT_N_NAZAD,
    IDX_TMR_MTZR_IN_N_NAZAD_PR,   IDX_TMR_MTZR_OUT_N_NAZAD_PR,
    IDX_TMR_MTZR_IN_PO_NAPRUZI,   IDX_TMR_MTZR_OUT_PO_NAPRUZI,
    IDX_TMR_MTZR_IN_PO_NAPRUZI_PR,IDX_TMR_MTZR_OUT_PO_NAPRUZI_PR,
    IDX_TMR_MTZR_IN_VVID_PR,      IDX_TMR_MTZR_OUT_VVID_PR,


}; 



#endif

